# Generated by Django 5.0.3 on 2024-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_donation',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='phone',
        ),
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='donor',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='zip_code',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
