# Generated by Django 5.0.3 on 2024-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donor_blood_group_alter_donor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
