# Generated by Django 5.0.3 on 2024-05-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_donor_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
